Bugfix gear shift to neutral
SzFMV2022-Tavasz/AutomatedCar-A pull request #82
Opened 2022-04-12 17:56 UTC by zsoltelekes09

2022-04-14 13:57 UTC, mrobert3456 reviewed
Jónak tűnik összességében, csak észrevettem, hogy most üresben gyorsabban lassul az autó, mint mikor sebességben van. Ezt esetleg tudnád korrigálni ha nem gond, hogy ugyanúgy lassuljon?

2022-04-15 09:59 UTC, MoKrisz requested changes
Nagyon szuper javítás, majd még rá kellene nézni arra is, hogy ne csak reverse --> neutral váltásnál legyen megoldva, hanem akkor is, ha a reverse --> neutral váltás után driveba váltunk. Ekkor még sajnos előjön a hiba

2022-04-15 10:01 UTC, MoKrisz commented
@zsoltelekes09  @mrobert3456  A lassulás a powertrainben lett megírva általam, szerintem ennél a jegynél nem kell vele foglalkozni. Direkt csináltam így, hogy gyorsabban lassuljon üresben, mint sebességben, a dinamikus lassulás miatt.

2022-04-15 19:36 UTC, zsoltelekes09 commented
> Nagyon szuper javítás, majd még rá kellene nézni arra is, hogy ne csak reverse --> neutral váltásnál legyen megoldva, hanem akkor is, ha a reverse --> neutral váltás után driveba váltunk. Ekkor még sajnos előjön a hiba

Köszi! Javítottam amit írtál :)

2022-04-24 14:57 UTC, MoKrisz approved these changes

2022-04-24 14:57 UTC, MoKrisz commented
Szuperül működik minden, köszi! :)

2022-04-24 14:58 UTC, mrobert3456 reviewed
Jó lett köszi

2022-04-24 14:58 UTC, merged